# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-18 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(default='\u65e5\u8bb0', to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
