# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 12:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180118_1331'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='\u7528\u6237')),
                ('comm_ip', models.GenericIPAddressField(verbose_name='ip')),
                ('comm_mail', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('comm_cont', models.CharField(max_length=54, verbose_name='\u5185\u5bb9')),
                ('comm_date', models.DateField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('status', models.CharField(choices=[('f', 'False'), ('t', 'True')], max_length=1, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u94fe\u63a5\u540d\u79f0')),
                ('link_url', models.URLField(verbose_name='\u94fe\u63a5\u5730\u5740')),
                ('link_des', models.CharField(max_length=54, verbose_name='\u94fe\u63a5\u63cf\u8ff0')),
                ('status', models.CharField(choices=[('f', 'False'), ('t', 'true')], max_length=1, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_ip', models.GenericIPAddressField(verbose_name='ip')),
                ('mess_nc', models.CharField(max_length=50, verbose_name='\u6635\u79f0')),
                ('mess_mail', models.EmailField(max_length=254, verbose_name='\u90ae\u7bb1')),
                ('mess_cont', models.CharField(max_length=54, verbose_name='\u7559\u8a00\u5185\u5bb9')),
                ('mess_date', models.DateField(auto_now_add=True, verbose_name='\u53d1\u8868\u65f6\u95f4')),
                ('status', models.CharField(choices=[('f', 'False'), ('t', 'true')], max_length=1, verbose_name='\u72b6\u6001')),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='cont_img',
            field=models.ImageField(default='images/defaut.jpg', upload_to='images', verbose_name='\u5185\u5bb9\u4e3b\u56fe'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='admin', max_length=16, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('d', 'Draft'), ('p', 'Published')], max_length=1, verbose_name='\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='tag',
            field=models.ManyToManyField(default='\u65e5\u8bb0', null=True, to='blog.Tag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, verbose_name='\u6807\u7b7e'),
        ),
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog', verbose_name='\u535a\u5ba2'),
        ),
    ]
