# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-20 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180120_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cont_img',
            field=models.ImageField(default='images/defaut.jpg', upload_to='/images/', verbose_name='\u5185\u5bb9\u4e3b\u56fe'),
        ),
    ]
